In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("/content/movies_metadata.csv", low_memory=False, on_bad_lines='warn')

In [4]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42640 entries, 0 to 42639
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  42640 non-null  object
 1   belongs_to_collection  4264 non-null   object
 2   budget                 42640 non-null  object
 3   genres                 42640 non-null  object
 4   homepage               7331 non-null   object
 5   id                     42640 non-null  object
 6   imdb_id                42624 non-null  object
 7   original_language      42633 non-null  object
 8   original_title         42640 non-null  object
 9   overview               41812 non-null  object
 10  popularity             42635 non-null  object
 11  poster_path            42307 non-null  object
 12  production_companies   42637 non-null  object
 13  production_countries   42637 non-null  object
 14  release_date           42570 non-null  object
 15  revenue                42634 non-null  float64
 16  runtime                42423 non-null  float64
 17  spoken_languages       42634 non-null  object
 18  status                 42568 non-null  object
 19  tagline                19680 non-null  object
 20  title                  42640 non-null  object
 21  video                  42633 non-null  object
 22  vote_average           42633 non-null  float64
 23  vote_count             42633 non-null  float64
dtypes: float64(4), object(20)
memory usage: 7.8+ MB

In [11]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [12]:
df.shape

(42640, 24)

In [13]:
df.isnull().sum()

adult                        0
belongs_to_collection    38376
budget                       0
genres                       0
homepage                 35309
id                           0
imdb_id                     16
original_language            7
original_title               0
overview                   828
popularity                   5
poster_path                333
production_companies         3
production_countries         3
release_date                70
revenue                      6
runtime                    217
spoken_languages             6
status                      72
tagline                  22960
title                        0
video                        7
vote_average                 7
vote_count                   7
dtype: int64

In [14]:
df = df.drop_duplicates().reset_index(drop = True)

In [15]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [16]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
42619,Mo Mandel: Negative Reinforcement,Mo Mandel takes the stage in his first hour-lo...,"[{'id': 35, 'name': 'Comedy'}]",NaN,0.0,0.083584
42620,Kathleen Madigan: Bothering Jesus,Kathleen Madigan's stand up special.,"[{'id': 35, 'name': 'Comedy'}]",NaN,6.0,0.182834
42621,Dan Levy: Lion,Dan Levy works his way from a zebra to a lion ...,"[{'id': 35, 'name': 'Comedy'}]",NaN,0.0,0.062949
42622,Aries Spears: Comedy Blueprint,Armed with his ferociously aggressive style of...,"[{'id': 35, 'name': 'Comedy'}]",NaN,0.0,0.147048
42623,nan,Detroit native Tony T. Roberts returns to his ...,"[{'id': 35, 'name': 'Comedy'}]",NaN,NaN,0.107507

In [17]:
df.isnull().sum()

title               0
overview          828
genres              0
tagline         22949
vote_average        7
popularity          5
dtype: int64

In [18]:
df = df.dropna(subset = ["title"])

In [ ]:
df["popularity"] = pd.to_numeric(
    df["popularity"],
    errors="coerce"
)

df["vote_average"] = pd.to_numeric(
    df["vote_average"],
    errors="coerce"
)

df = df[
    (df["vote_average"] >= 6)
    & (df["popularity"] >= 10)
]

df = df.reset_index(drop=True)

print(df.shape)

In [22]:
df["overview"] = df["overview"].fillna("")

In [21]:
import ast
df["genres"] = df["genres"].apply(lambda x: " ".join([i["name"] for i in ast.literal_eval(x)]))

In [20]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [19]:
df["tagline"] = df["tagline"].fillna("")

In [23]:
import re

df["title"] = df["title"].astype(str)

df["title"] = df["title"].apply(
    lambda x: re.sub(r'^[^A-Za-z0-9]+', '', x)
)

In [25]:
special_titles = df[
    df["title"].str.match(r'^[^A-Za-z0-9]', na=False)
]

print(special_titles["title"].head(20))
print("Count:", len(special_titles))

Series([], Name: title, dtype: object)
Count: 0

In [26]:
title = df[df["title"].str.contains("Women Art Revolution", case=False, na=False)]["title"].iloc[0]

print("Title:", repr(title))
print("First character:", repr(title[0]))
print("Is alphanumeric?", title[0].isalnum())

Title: 'Women Art Revolution'
First character: 'W'
Is alphanumeric? True

In [27]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [28]:
df["tags"] = df["overview"] + " " + df["genres"] + " " + df["tagline"]

In [29]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [30]:
df["tags"][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [31]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [32]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [33]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [34]:
def preprocess_text(text):
  text = str(text.lower())
  text = re.sub(r'[^a-zA-Z\s]' , "" , text)
  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [lemmatizer.lemmatize(word) for word in words]
  return " ".join(words)

In [35]:
df["tags"] = df["tags"].apply(preprocess_text)

In [37]:
df["tags"][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [38]:
df = df.reset_index(drop = True)

In [39]:
indices = pd.Series(df.index , index=df['title'])
indices

title
Toy Story                                0
Jumanji                                  1
Grumpier Old Men                         2
Waiting to Exhale                        3
Father of the Bride Part II              4
                                     ...
Mo Mandel: Negative Reinforcement    42619
Kathleen Madigan: Bothering Jesus    42620
Dan Levy: Lion                       42621
Aries Spears: Comedy Blueprint       42622
nan                                  42623
Length: 42624, dtype: int64

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2) , stop_words='english')

In [42]:
tfidf_matrix = tfidf.fit_transform(df["tags"])

In [43]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1056386 stored elements and shape (42624, 5000)>

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
def recommend(title , n = 10):
  if title not in indices :
    return ["Movie not Found"]
  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx] , tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df["title"].iloc[similar_idx]

In [46]:
recommend("Toy Story")

28974                    Superstar Goofy
2996                         Toy Story 2
21921               Toy Story of Terror!
25788                    Partysaurus Rex
24512                  Hawaiian Vacation
31497                          Bar Sport
37287    Father of Four: Never Gives Up!
14339            Darkness/Light/Darkness
24310             Moomins on the Riviera
21983                         Free Birds
Name: title, dtype: object

In [47]:
recommend("i Saw the devil")

['Movie not Found']

In [49]:
import pickle
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf , open('tfidf.pkl','wb'))